### ISSUE TITLE
License

### ISSUE THREAD

**Issue by davidmuggleton** [jonathanraftery/bullhorn-rest-client#15]
Hi there,

I can't seem to find any license information for this project, are you able to confirm what license the code is under?

Thanks!

**Comment by jonathanraftery** [comment]
Ah, thanks. The composer package specifies the MIT license, but there should be a section in the README on this as well. Will get that added in.

**Comment by davidmuggleton** [comment]
Thanks for clarifying 👍

**Comment by jonathanraftery** [comment]
License info has been added in /LICENSE
