### ISSUE TITLE
PHP8 support

### ISSUE THREAD

**Issue by cappadaan** [jonathanraftery/bullhorn-rest-client#17]
Can you add PHP8 support? 

    - jonathanraftery/bullhorn-rest-client is locked to version 1.3.1 and an update of this package was not requested.
    - jonathanraftery/bullhorn-rest-client 1.3.1 requires php ^7.3 -> your php version (8.0.6; overridden via config.platform, same as actual) does not satisfy that requirement.

**Comment by jonathanraftery** [comment]
Added PHP 8 support in version 1.4.0
